In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import cv2
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.linear_model import Lasso
# from scikeras.wrappers import KerasClassifier, KerasRegressor
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Read datasets

In [2]:
readDataPath = './resources/'
# Read datasets
landmarksJaffe = pd.read_csv(readDataPath+'features/landmarksJaffe.csv')
print(f"landmarksJaffe shape: {landmarksJaffe.shape}")
landmarksKdef = pd.read_csv(readDataPath+'features/landmarksKDEF.csv')
print(f"landmarksKdef.shape: {landmarksKdef.shape}")
landmarksCKplus = pd.read_csv(readDataPath+'features/landmarksCKPLUS.csv')
print(f"landmarksCKplus.shape: {landmarksCKplus.shape}")
landmarksCustom = pd.read_csv(readDataPath+'features/landmarksCustom.csv')
print(f"landmarksCustom.shape: {landmarksCustom.shape}")
gaborPCA = pd.read_csv(readDataPath+'features/gaborPCA.csv')
print(f"gaborPCA shape: {gaborPCA.shape}")

landmarksJaffe shape: (213, 207)
landmarksKdef.shape: (2917, 207)
landmarksCKplus.shape: (840, 207)
landmarksCustom.shape: (118, 207)
gaborPCA shape: (4088, 40)


# Concatenate 3D landmark datasets

In [3]:
# stack datasets
emotionLandmarks = pd.concat([landmarksJaffe, landmarksKdef, landmarksCKplus, landmarksCustom], axis=0)
print(f"emotionLandmarks shape: {emotionLandmarks.shape}")

emotionLandmarks shape: (4088, 207)


# Split 3D landmark Training data & Labels

In [4]:
X_landmarks = emotionLandmarks.drop('emotion', axis=1)
y = emotionLandmarks['emotion'].astype('int8')
print(f"X_landmarks shape: {X_landmarks.shape}")

X_landmarks shape: (4088, 206)


# Scaling 3D landmarks & Gabor datasets

In [5]:
scaler = MinMaxScaler()

# 3D landmark scaling
X_landmarks_scaled = scaler.fit_transform(X_landmarks)
print(f"X_3D_scaled Shape = {np.shape(X_landmarks_scaled)}")
# print(f"scaler min = {scaler.data_min_}, scaler max = {scaler.data_max_}")

# # save min/max values of each feature
# with open('./datasets/combiModels/scalerParams_svm_pp.pkl', 'wb') as file:
#     params = {'minValues': scaler.data_min_, 'maxValues': scaler.data_max_}
#     pickle.dump(params, file)
# file.close()

# Gabor scaling
gaborPCA_scaled = scaler.fit_transform(gaborPCA)
print(f"gaborPCA_scaled Shape = {np.shape(gaborPCA_scaled)}")
# # save min/max values of each feature
# with open('./datasets/combiModels/scalerParamsGabor_svm_pp.pkl', 'wb') as file:
#     params = {'minValues': scaler.data_min_, 'maxValues': scaler.data_max_}
#     pickle.dump(params, file)
# file.close()

X_3D_scaled Shape = (4088, 206)
gaborPCA_scaled Shape = (4088, 40)


# Dimensionality Reduction of 3D landmark dataset

In [6]:
n_components = 120
pca = PCA(n_components= n_components)
X_landmarks_scaled_pca = pca.fit_transform(X_landmarks_scaled)
print(f"X_3D_scaled_pca shape: {X_landmarks_scaled_pca.shape}, type: {type(X_landmarks_scaled_pca)}")

# # Save the fitted PCA model to a file
# with open(readDataPath+'combiModels/pca_svm_pp.pkl', 'wb') as file:
#     pickle.dump(pca, file)
# file.close()

print(f"Explained variance: {round(np.cumsum(pca.explained_variance_ratio_ * 100)[-1],2)}%")

X_3D_scaled_pca shape: (4088, 120), type: <class 'numpy.ndarray'>
Explained variance: 99.3%


# Concatenate & Shuffle datasets

In [7]:
print(f"X_landmarks_scaled_pca shape: {X_landmarks_scaled_pca.shape}, type: {type(X_landmarks_scaled_pca)}")
print(f"gaborPCA_scaled shape: {gaborPCA_scaled.shape}, type: {type(gaborPCA_scaled)}")
print(f"y shape: {y.shape}, type: {type(y)}")

# concatenate landmark and gabor datasets
X_landmarks_gabor_scaled_pca = np.concatenate((X_landmarks_scaled_pca, gaborPCA_scaled), axis=1)

# shuffle
X_landmarks_gabor_scaled_pca_shuffled, y_shuffled = shuffle(X_landmarks_gabor_scaled_pca, y, random_state=512)

print(f"X_landmarks_gabor_scaled_pca_shuffled shape: {X_landmarks_gabor_scaled_pca_shuffled.shape}, type: {type(X_landmarks_gabor_scaled_pca_shuffled)}")
print(f"y shape: {y_shuffled.shape}, type: {type(y_shuffled)}")

X_landmarks_scaled_pca shape: (4088, 120), type: <class 'numpy.ndarray'>
gaborPCA_scaled shape: (4088, 40), type: <class 'numpy.ndarray'>
y shape: (4088,), type: <class 'pandas.core.series.Series'>
X_landmarks_gabor_scaled_pca_shuffled shape: (4088, 160), type: <class 'numpy.ndarray'>
y shape: (4088,), type: <class 'pandas.core.series.Series'>


# Check label count

In [8]:
# string labels
emo = ['angry', 
        'disgust',
        'fear',
        'happy',
        'sad',
        'surprised',
        'neutral'
]

# count classes
emotions, counts =np.unique(y_shuffled, return_counts=True)
for c, count in zip(emotions, counts):
    print(f"{emo[c]} count = {count}")

angry count = 569
disgust count = 602
fear count = 538
happy count = 654
sad count = 518
surprised count = 664
neutral count = 543


# Build and Validate Single run SVM-RBF

In [9]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_landmarks_gabor_scaled_pca_shuffled, y_shuffled, test_size=0.1, shuffle=True, random_state=190)

# train model
svmClf = SVC(kernel ='rbf', C=7.5, gamma=0.35)
hist = svmClf.fit(X_train, y_train)

# Calculate training accuracy
y_train_pred = svmClf.predict(X_train)
train_acc = accuracy_score(y_train, y_train_pred)

# Calculate validation accuracy
y_val_pred = svmClf.predict(X_test)
val_acc = accuracy_score(y_test, y_val_pred)

print(f"Training accuracy: {round(train_acc*100,2)}%, Validation accuracy: {round(val_acc*100,2)}%")

Training accuracy: 100.0%, Validation accuracy: 89.24%


# Confusion Matrix Typical Case

In [10]:
y_pred = svmClf.predict(X_test)
cm = confusion_matrix(y_true=y_test, y_pred=y_pred)
TP = cm.diagonal().sum()
totalIns = cm.sum()

print(f"Number of Test Instances= {totalIns}")
print(f"Accuracy= {round((TP/totalIns)*100,2)}%")
print('Confusion Matrix')
print(cm)

Number of Test Instances= 409
Accuracy= 89.24%
Confusion Matrix
[[45  3  1  0  1  0  1]
 [ 3 43  2  0  1  0  0]
 [ 2  1 43  1  0  9  0]
 [ 0  0  0 64  0  0  0]
 [ 2  2  2  0 49  0  4]
 [ 0  0  3  1  1 64  0]
 [ 1  0  1  0  2  0 57]]


# Grid Search Best Estimator for SVM-RBF

In [11]:
pipeline = Pipeline([
                        ('svm', SVC(kernel ='rbf', probability=True, random_state=42)),
])

# define the hyperparameters to search over
param_grid = {
    'svm__C': [7.5],
    'svm__gamma': [0.3,0.35],
}

# perform a grid search to find the best hyperparameters
grid_search = GridSearchCV(pipeline, param_grid=param_grid, cv=10, verbose=2)
hist = grid_search.fit(X_landmarks_gabor_scaled_pca_shuffled, y_shuffled)

# print the best hyperparameters and the corresponding score
print(f"Best hyperparameters: {grid_search.best_params_}")
print(f"Best score: {round(grid_search.best_score_,4)*100}%")

Fitting 10 folds for each of 2 candidates, totalling 20 fits
[CV] END .........................svm__C=7.5, svm__gamma=0.3; total time=   3.7s
[CV] END .........................svm__C=7.5, svm__gamma=0.3; total time=   3.7s
[CV] END .........................svm__C=7.5, svm__gamma=0.3; total time=   3.7s
[CV] END .........................svm__C=7.5, svm__gamma=0.3; total time=   3.7s
[CV] END .........................svm__C=7.5, svm__gamma=0.3; total time=   3.7s
[CV] END .........................svm__C=7.5, svm__gamma=0.3; total time=   3.7s
[CV] END .........................svm__C=7.5, svm__gamma=0.3; total time=   3.7s
[CV] END .........................svm__C=7.5, svm__gamma=0.3; total time=   3.9s
[CV] END .........................svm__C=7.5, svm__gamma=0.3; total time=   3.8s
[CV] END .........................svm__C=7.5, svm__gamma=0.3; total time=   3.7s
[CV] END ........................svm__C=7.5, svm__gamma=0.35; total time=   4.2s
[CV] END ........................svm__C=7.5, svm

# K-Fold Cross Validation

In [12]:
k=10
svmClfCV = SVC(kernel ='rbf', C=7.5, gamma=0.35)
scores = cross_val_score(svmClfCV, X_landmarks_gabor_scaled_pca_shuffled, y_shuffled, cv=k)
print(f"Mean Cross-Validation Score: {round(np.mean(scores)*100,2)}%") #84.59

Mean Cross-Validation Score: 85.93%


# Save Serialized Model

In [13]:
# bestModel = grid_search.best_estimator_
# with open(readDataPath+'combiModels/modelSvmRbf_pp.pkl', 'wb') as file:
#     pickle.dump(bestModel,file)

# file.close()